ekyna_commerce_attribute_group_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.attribute_group.controller:homeAction" }
    methods: [GET]

ekyna_commerce_attribute_group_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.attribute_group.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_attribute_group_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.attribute_group.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_attribute_group_admin_show:
    path: /{attributeGroupId}/show
    defaults: { _controller: "ekyna_commerce.attribute_group.controller:showAction" }
    methods: [GET]
    requirements:
        attributeGroupId: \d+

ekyna_commerce_attribute_group_admin_edit:
    path: /{attributeGroupId}/edit
    defaults: { _controller: "ekyna_commerce.attribute_group.controller:editAction" }
    methods: [GET|POST]
    requirements:
        attributeGroupId: \d+

ekyna_commerce_attribute_group_admin_remove:
    path: /{attributeGroupId}/remove
    defaults: { _controller: "ekyna_commerce.attribute_group.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        attributeGroupId: \d+

ekyna_commerce_attribute_admin:
    resource: attribute.yml
    prefix: /{attributeGroupId}/attributes
