ekyna_commerce_attribute_set_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.attribute_set.controller:homeAction" }
    methods: [GET]

ekyna_commerce_attribute_set_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.attribute_set.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_attribute_set_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.attribute_set.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_attribute_set_admin_show:
    path: /{attributeSetId}/show
    defaults: { _controller: "ekyna_commerce.attribute_set.controller:showAction" }
    methods: [GET]
    requirements:
        attributeSetId: \d+

ekyna_commerce_attribute_set_admin_edit:
    path: /{attributeSetId}/edit
    defaults: { _controller: "ekyna_commerce.attribute_set.controller:editAction" }
    methods: [GET|POST]
    requirements:
        attributeSetId: \d+

ekyna_commerce_attribute_set_admin_remove:
    path: /{attributeSetId}/remove
    defaults: { _controller: "ekyna_commerce.attribute_set.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        attributeSetId: \d+
